name: py311
channels:
  - defaults
dependencies:
  - executing=0.8.3=pyhd3eb1b0_0
  - pillow=11.1.0=py311h096bfcc_0
  - pandas
  - anyio=4.7.0=py311haa95532_0
  - lcms2=2.16=hb4a4139_0
  - libbrotlienc=1.0.9=h827c3e9_9
  - matplotlib-inline=0.1.6=py311haa95532_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pyparsing=3.2.0=py311haa95532_0
  - packaging=25.0=py311haa95532_0
  - jupyter_server=2.16.0=py311haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - typing-extensions=4.15.0=py311haa95532_0
  - jedi=0.19.2=py311haa95532_0
  - pyqt6-sip=13.9.1=py311h02ab6af_2
  - utf8proc=2.6.1=h2bbff1b_1
  - jupyterlab_widgets=3.0.15=py311haa95532_0
  - pycparser=2.21=pyhd3eb1b0_0
  - tk=8.6.15=hf199647_0
  - libxml2=2.13.8=h866ff63_0
  - matplotlib-base=3.10.5=py311h43afe63_0
  - winpty=0.4.3=4
  - yaml=0.2.5=he774522_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - kiwisolver=1.4.8=py311h5da7b33_0
  - aws-c-http=0.10.4=h02ab6af_0
  - comm=0.2.1=py311haa95532_0
  - python-docx=1.2.0=pyhff2d567_0
  - qtwebsockets=6.7.3=h885b0b7_1
  - poppler=24.09.0=h6558a74_1
  - certifi=2026.1.4
  - mkl-service=2.4.0=py311h827c3e9_2
  - ucrt=10.0.22621.0=haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - libprotobuf=5.29.3=h65a231f_1
  - httpx=0.28.1=py311haa95532_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - threadpoolctl=3.5.0=py311h746a85d_0
  - jupyter-lsp=2.2.5=py311haa95532_0
  - jupyterlab_pygments=0.3.0=py311haa95532_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - pixman=0.46.4=h5112557_1
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h62dcd97_0
  - python-fastjsonschema=2.20.0=py311haa95532_0
  - mkl_random=1.2.8=py311hea22821_0
  - mistune=3.1.2=py311haa95532_0
  - parso=0.8.4=py311haa95532_0
  - libkrb5=1.21.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - pywin32=311=py311h885b0b7_0
  - et_xmlfile=2.0.0=py311haa95532_0
  - jupyter_server_terminals=0.5.3=py311haa95532_0
  - python-dateutil=2.9.0post0=py311haa95532_2
  - pywinpty=2.0.15=py311h72d21ff_0
  - pyqt=6.7.1=py311h378bd72_2
  - lerc=3.0=hd77b12b_0
  - ipython_pygments_lexers=1.1.1=py311haa95532_0
  - asttokens=3.0.0=py311haa95532_0
  - cairo=1.18.4=he9e932c_0
  - jsonschema=4.25.0=py311haa95532_0
  - qtdeclarative=6.7.3=h885b0b7_1
  - libgrpc=1.71.0=hf4237ab_0
  - rfc3339-validator=0.1.4=py311haa95532_0
  - websocket-client=1.8.0=py311haa95532_0
  - tzdata=2025b=h04d1e81_0
  - nb_conda_kernels=2.5.2=py311haa95532_1
  - prometheus_client=0.21.1=py311haa95532_0
  - urllib3=2.5.0=py311haa95532_0
  - requests=2.32.5
  - prompt-toolkit=3.0.43=py311haa95532_0
  - libre2-11=2024.07.02=h5da7b33_0
  - mkl=2023.1.0=h6b88ed4_46358
  - snappy=1.2.1=hcdb6601_0
  - libssh2=1.11.1=h2addb87_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - attrs=24.3.0=py311haa95532_0
  - matplotlib=3.10.5=py311haa95532_0
  - brotlicffi=1.0.9.2=py311h5da7b33_1
  - glog=0.5.0=hd77b12b_1
  - pygments=2.19.1=py311haa95532_0
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - zeromq=4.3.5=hd77b12b_0
  - bottleneck=1.4.2=py311h57dcf0c_0
  - jsonschema-specifications=2023.7.1=py311haa95532_0
  - scipy=1.16.0=py311h242c13b_0
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - pytz=2025.2=py311haa95532_0
  - openssl=3.6.1
  - libpq=17.4=h4a159e6_2
  - psutil=5.9.0=py311h827c3e9_1
  - bzip2=1.0.8=h2bbff1b_6
  - plotly=6.3.0=py311hbc747e5_0
  - sqlite=3.50.2=hda9a48d_1
  - openpyxl=3.1.5
  - overrides=7.4.0=py311haa95532_0
  - widgetsnbextension=4.0.13=py311haa95532_0
  - libwebp-base=1.3.2=h3d04722_1
  - qtsvg=6.7.3=h9d4b640_1
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - bleach=6.2.0=py311haa95532_0
  - nbformat=5.10.4=py311haa95532_0
  - jupyter_events=0.12.0=py311haa95532_0
  - jinja2=3.1.6=py311haa95532_0
  - wcwidth=0.2.13=py311haa95532_0
  - libdeflate=1.17=h2bbff1b_1
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - vc14_runtime=14.44.35208=h4927774_10
  - numexpr=2.11.0=py311hdb065b2_0
  - httpcore=1.0.9=py311haa95532_0
  - async-lru=2.0.4=py311haa95532_0
  - aws-checksums=0.2.7=h02ab6af_1
  - libcurl=8.15.0=h2300eb9_0
  - platformdirs=4.3.7=py311haa95532_0
  - seaborn=0.13.2=py311haa95532_3
  - tbb=2021.8.0=h59b6b97_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - nbclient=0.10.2=py311haa95532_0
  - icu=73.1=h6c2663c_0
  - pyzmq=27.1.0
  - referencing=0.30.2=py311haa95532_0
  - ipython=9.1.0=py311haa95532_0
  - pyyaml=6.0.2=py311h827c3e9_0
  - tornado=6.5.4
  - traitlets=5.14.3=py311haa95532_0
  - brotli-python=1.0.9=py311h5da7b33_9
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - numpy
  - jupyter_core=5.8.1=py311haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - debugpy=1.8.11=py311h5da7b33_0
  - contourpy=1.3.1=py311h214f63a_0
  - markupsafe=3.0.2=py311h827c3e9_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - qtbase=6.7.3=hd088775_4
  - sip=6.10.0=py311h5da7b33_0
  - libtiff=4.5.1=hd77b12b_0
  - blas=1.0=mkl
  - libiconv=1.18=hc1393d2_2
  - arrow-cpp=19.0.0=h800e9c8_5
  - rpds-py=0.22.3=py311h636fa0f_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - idna=3.7=py311haa95532_0
  - re2=2024.07.02=h214f63a_0
  - tinycss2=1.4.0=py311haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - six=1.17.0=py311haa95532_0
  - h11=0.16.0=py311haa95532_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - ipywidgets=8.1.5=py311haa95532_0
  - qttools=6.7.3=hcb596f7_1
  - send2trash=1.8.2=py311haa95532_1
  - aws-c-auth=0.9.0=h02ab6af_2
  - narwhals=1.31.0=py311haa95532_1
  - beautifulsoup4=4.14.3
  - fonttools=4.55.3=py311h827c3e9_0
  - jpeg=9e=h827c3e9_3
  - icc_rt=2022.1.0=h6049295_2
  - decorator=5.1.1=pyhd3eb1b0_0
  - json5=0.9.25=py311haa95532_0
  - webencodings=0.5.1=py311haa95532_1
  - nbconvert-core=7.16.6=py311haa95532_0
  - libboost=1.82.0=h3399ecb_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - ca-certificates=2026.1.4
  - mkl_fft=1.3.11=py311h827c3e9_0
  - unicodedata2=15.1.0=py311h827c3e9_1
  - typing_extensions=4.15.0=py311haa95532_0
  - python=3.11.13=h981015d_0
  - babel=2.16.0=py311haa95532_0
  - numpy-base=2.0.1=py311hd01c5d8_1
  - pcre2=10.42=h0ff8eda_1
  - argon2-cffi-bindings=21.2.0=py311h827c3e9_1
  - colorama=0.4.6=py311haa95532_0
  - notebook-shim=0.2.4=py311haa95532_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - orc=2.1.1=hd1c1d5c_0
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - libglib=2.84.2=h405b238_0
  - nest-asyncio=1.6.0=py311haa95532_0
  - pysocks=1.7.1=py311haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - c-ares=1.34.5=h731ff69_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - libbrotlidec=1.0.9=h827c3e9_9
  - libthrift=0.15.0=ha2884a9_3
  - rfc3986-validator=0.1.1=py311haa95532_0
  - libxslt=1.1.43=h25c3957_0
  - soupsieve=2.5=py311haa95532_0
  - sniffio=1.3.0=py311haa95532_0
  - zstd=1.5.6=h8880b57_0
  - python-json-logger=3.2.1=py311haa95532_0
  - joblib=1.5.1=py311haa95532_0
  - aws-c-io=0.21.4=h02ab6af_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - qtwebchannel=6.7.3=h885b0b7_1
  - vc=14.3=h2df5915_10
  - boost-cpp=1.82.0=h59b6b97_2
  - pypdf
prefix: C:\Users\julian.diaz\.conda\envs\py311
